//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Win.ProxyDocumento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyDocumento.IDocService")]
    public interface IDocService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDocService/GuardarDocumento")]
        void GuardarDocumento(NorthWind.Entity.DocumentoBE oDocumentoDTO);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDocService/GuardarDocumento")]
        System.Threading.Tasks.Task GuardarDocumentoAsync(NorthWind.Entity.DocumentoBE oDocumentoDTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocServiceChannel : NorthWind.Win.ProxyDocumento.IDocService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocServiceClient : System.ServiceModel.ClientBase<NorthWind.Win.ProxyDocumento.IDocService>, NorthWind.Win.ProxyDocumento.IDocService {
        
        public DocServiceClient() {
        }
        
        public DocServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GuardarDocumento(NorthWind.Entity.DocumentoBE oDocumentoDTO) {
            base.Channel.GuardarDocumento(oDocumentoDTO);
        }
        
        public System.Threading.Tasks.Task GuardarDocumentoAsync(NorthWind.Entity.DocumentoBE oDocumentoDTO) {
            return base.Channel.GuardarDocumentoAsync(oDocumentoDTO);
        }
    }
}
