//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Win.ProxyMantenimiento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyMantenimiento.IManService")]
    public interface IManService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromCliente", ReplyAction="http://tempuri.org/IManService/SelectAllFromClienteResponse")]
        NorthWind.Entity.TbClienteBE[] SelectAllFromCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromCliente", ReplyAction="http://tempuri.org/IManService/SelectAllFromClienteResponse")]
        System.Threading.Tasks.Task<NorthWind.Entity.TbClienteBE[]> SelectAllFromClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromCategoria", ReplyAction="http://tempuri.org/IManService/SelectAllFromCategoriaResponse")]
        NorthWind.Entity.TbCategoriaBE[] SelectAllFromCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromCategoria", ReplyAction="http://tempuri.org/IManService/SelectAllFromCategoriaResponse")]
        System.Threading.Tasks.Task<NorthWind.Entity.TbCategoriaBE[]> SelectAllFromCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromProducto", ReplyAction="http://tempuri.org/IManService/SelectAllFromProductoResponse")]
        NorthWind.Entity.TbProductoBE[] SelectAllFromProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromProducto", ReplyAction="http://tempuri.org/IManService/SelectAllFromProductoResponse")]
        System.Threading.Tasks.Task<NorthWind.Entity.TbProductoBE[]> SelectAllFromProductoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManServiceChannel : NorthWind.Win.ProxyMantenimiento.IManService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManServiceClient : System.ServiceModel.ClientBase<NorthWind.Win.ProxyMantenimiento.IManService>, NorthWind.Win.ProxyMantenimiento.IManService {
        
        public ManServiceClient() {
        }
        
        public ManServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NorthWind.Entity.TbClienteBE[] SelectAllFromCliente() {
            return base.Channel.SelectAllFromCliente();
        }
        
        public System.Threading.Tasks.Task<NorthWind.Entity.TbClienteBE[]> SelectAllFromClienteAsync() {
            return base.Channel.SelectAllFromClienteAsync();
        }
        
        public NorthWind.Entity.TbCategoriaBE[] SelectAllFromCategoria() {
            return base.Channel.SelectAllFromCategoria();
        }
        
        public System.Threading.Tasks.Task<NorthWind.Entity.TbCategoriaBE[]> SelectAllFromCategoriaAsync() {
            return base.Channel.SelectAllFromCategoriaAsync();
        }
        
        public NorthWind.Entity.TbProductoBE[] SelectAllFromProducto() {
            return base.Channel.SelectAllFromProducto();
        }
        
        public System.Threading.Tasks.Task<NorthWind.Entity.TbProductoBE[]> SelectAllFromProductoAsync() {
            return base.Channel.SelectAllFromProductoAsync();
        }
    }
}
