//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Win.ProxyManIis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventArgs", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NorthWind.Entity.TbProductoBE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NorthWind.Entity.TbClienteBE))]
    public partial class EventArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyManIis.IManService")]
    public interface IManService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromCliente", ReplyAction="http://tempuri.org/IManService/SelectAllFromClienteResponse")]
        System.Collections.Generic.List<NorthWind.Entity.TbClienteBE> SelectAllFromCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromCliente", ReplyAction="http://tempuri.org/IManService/SelectAllFromClienteResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<NorthWind.Entity.TbClienteBE>> SelectAllFromClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromCategoria", ReplyAction="http://tempuri.org/IManService/SelectAllFromCategoriaResponse")]
        System.Collections.Generic.List<NorthWind.Entity.TbCategoriaBE> SelectAllFromCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromCategoria", ReplyAction="http://tempuri.org/IManService/SelectAllFromCategoriaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<NorthWind.Entity.TbCategoriaBE>> SelectAllFromCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromProducto", ReplyAction="http://tempuri.org/IManService/SelectAllFromProductoResponse")]
        System.Collections.Generic.List<NorthWind.Entity.TbProductoBE> SelectAllFromProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManService/SelectAllFromProducto", ReplyAction="http://tempuri.org/IManService/SelectAllFromProductoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<NorthWind.Entity.TbProductoBE>> SelectAllFromProductoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManServiceChannel : NorthWind.Win.ProxyManIis.IManService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManServiceClient : System.ServiceModel.ClientBase<NorthWind.Win.ProxyManIis.IManService>, NorthWind.Win.ProxyManIis.IManService {
        
        public ManServiceClient() {
        }
        
        public ManServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<NorthWind.Entity.TbClienteBE> SelectAllFromCliente() {
            return base.Channel.SelectAllFromCliente();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<NorthWind.Entity.TbClienteBE>> SelectAllFromClienteAsync() {
            return base.Channel.SelectAllFromClienteAsync();
        }
        
        public System.Collections.Generic.List<NorthWind.Entity.TbCategoriaBE> SelectAllFromCategoria() {
            return base.Channel.SelectAllFromCategoria();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<NorthWind.Entity.TbCategoriaBE>> SelectAllFromCategoriaAsync() {
            return base.Channel.SelectAllFromCategoriaAsync();
        }
        
        public System.Collections.Generic.List<NorthWind.Entity.TbProductoBE> SelectAllFromProducto() {
            return base.Channel.SelectAllFromProducto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<NorthWind.Entity.TbProductoBE>> SelectAllFromProductoAsync() {
            return base.Channel.SelectAllFromProductoAsync();
        }
    }
}
